document.addEventListener('DOMContentLoaded',()=>{console.log("Document loaded");const burger=document.querySelector('.burger');const navLinks=document.querySelector('.nav-links');if(burger&&navLinks){burger.addEventListener('click',function(){navLinks.classList.toggle('nav-active');this.classList.toggle('toggle');document.querySelectorAll('.nav-links li').forEach((link,index)=>{if(link.style.animation){link.style.animation=''}else{link.style.animation=`navLinkFade 0.5s ease forwards ${index / 7 + 0.3}s`}})})}else{console.error("Burger or nav-links element not found!")}
const navbar=document.querySelector('nav');if(navbar){navbar.classList.remove('scrolled');window.addEventListener('scroll',()=>{if(window.scrollY>50){navbar.classList.add('scrolled')}else{navbar.classList.remove('scrolled')}})}
window.addEventListener('load',function(){document.body.classList.add('loaded')});document.querySelectorAll('a[href^="#"]').forEach(anchor=>{anchor.addEventListener('click',function(e){e.preventDefault();const targetId=this.getAttribute('href');const targetElement=document.querySelector(targetId);if(targetElement){window.scrollTo({top:targetElement.offsetTop-70,behavior:'smooth'});if(navLinks&&navLinks.classList.contains('nav-active')){navLinks.classList.remove('nav-active');if(burger)burger.classList.remove('toggle');document.querySelectorAll('.nav-links li').forEach(link=>{link.style.animation=''})}}})});const contactForm=document.querySelector('#contactForm');if(contactForm){contactForm.addEventListener('submit',(e)=>{e.preventDefault();const lang=localStorage.getItem('language')||'en';let message='Thank you for your message! In a real website, this would be sent to our server.';if(window.translations&&window.translations[lang]&&window.translations[lang].formSubmitted){message=window.translations[lang].formSubmitted}
alert(message);contactForm.reset()})}
createScrollToTopButton();const ctaButton=document.querySelector('.cta-button');if(ctaButton){ctaButton.addEventListener('click',()=>{const servicesSection=document.querySelector('#services');if(servicesSection){window.scrollTo({top:servicesSection.offsetTop-70,behavior:'smooth'})}})}
initHeroSlideshow();initThemeToggle();initLanguageSelector();initEquipmentFilter();enhancePortfolio();addFavicon()});function addFavicon(){if(!document.querySelector('link[rel="icon"]')){const favicon=document.createElement('link');favicon.rel='icon';favicon.href='data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><text y="0.9em" font-size="90">🏭</text></svg>';document.head.appendChild(favicon)}}
function createScrollToTopButton(){if(document.querySelector('.scroll-top-btn'))return;const scrollBtn=document.createElement('button');scrollBtn.innerHTML='<i class="fas fa-arrow-up"></i>';scrollBtn.className='scroll-top-btn';document.body.appendChild(scrollBtn);scrollBtn.addEventListener('click',()=>{window.scrollTo({top:0,behavior:'smooth'})});window.addEventListener('scroll',()=>{if(window.pageYOffset>300){scrollBtn.style.display='block'}else{scrollBtn.style.display='none'}})}
function initHeroSlideshow(){const slides=document.querySelectorAll('.hero .slide');const dots=document.querySelectorAll('.nav-dot');if(!slides.length)return;let currentSlide=0;let slideInterval;const showSlide=(index)=>{slides.forEach(slide=>slide.classList.remove('active'));dots.forEach(dot=>dot.classList.remove('active'));slides[index].classList.add('active');dots[index].classList.add('active');currentSlide=index};const nextSlide=()=>{currentSlide=(currentSlide+1)%slides.length;showSlide(currentSlide)};if(slides.length>1){showSlide(0);slideInterval=setInterval(nextSlide,5000);dots.forEach((dot,index)=>{dot.addEventListener('click',()=>{clearInterval(slideInterval);showSlide(index);slideInterval=setInterval(nextSlide,5000)})})}}
function initThemeToggle(){const themeToggle=document.querySelector('.theme-toggle');const themeIcon=document.getElementById('theme-toggle-icon');if(!themeToggle||!themeIcon){console.error("Theme toggle elements not found");return}
const savedTheme=localStorage.getItem('theme')||'light';if(savedTheme==='dark'){document.body.classList.add('dark-mode');themeIcon.className='fas fa-sun'}else{document.body.classList.remove('dark-mode');themeIcon.className='fas fa-moon'}
themeToggle.addEventListener('click',function(e){e.preventDefault();const currentTheme=localStorage.getItem('theme')||'light';const newTheme=currentTheme==='light'?'dark':'light';localStorage.setItem('theme',newTheme);window.location.reload()})}
function initLanguageSelector(){const selectSelected=document.querySelector('.select-selected');const selectItems=document.querySelector('.select-items');const selectOptions=document.querySelectorAll('.select-item');if(!selectSelected||!selectItems||!selectOptions.length){console.error("Language selector elements not found");return}
const savedLanguage=localStorage.getItem('language')||'en';selectOptions.forEach(option=>{const lang=option.getAttribute('data-value');if(lang===savedLanguage){const label=selectSelected.querySelector('.lang-label');if(label){label.textContent=option.textContent}
option.classList.add('selected')}else{option.classList.remove('selected')}});selectSelected.addEventListener('click',function(e){e.stopPropagation();selectItems.classList.toggle('select-show');selectSelected.classList.toggle('active')});selectOptions.forEach(option=>{option.addEventListener('click',function(){const lang=this.getAttribute('data-value');const currentLang=localStorage.getItem('language')||'en';if(lang!==currentLang){const label=selectSelected.querySelector('.lang-label');if(label){label.textContent=this.textContent}
selectOptions.forEach(opt=>opt.classList.remove('selected'));this.classList.add('selected');localStorage.setItem('language',lang);selectItems.classList.remove('select-show');selectSelected.classList.remove('active');window.location.reload()}else{selectItems.classList.remove('select-show');selectSelected.classList.remove('active')}})});document.addEventListener('click',function(e){if(!selectSelected.contains(e.target)&&!selectItems.contains(e.target)){selectItems.classList.remove('select-show');selectSelected.classList.remove('active')}})}
function initEquipmentFilter(){const equipmentTabs=document.querySelectorAll('.equipment-tab');const equipmentItems=document.querySelectorAll('.equipment-item');if(!equipmentTabs.length||!equipmentItems.length)return;equipmentTabs.forEach(tab=>{tab.addEventListener('click',()=>{equipmentTabs.forEach(t=>t.classList.remove('active'));tab.classList.add('active');const category=tab.getAttribute('data-category');equipmentItems.forEach(item=>{if(category==='all'||item.getAttribute('data-category')===category){item.style.display='block'}else{item.style.display='none'}})})})}
function enhancePortfolio(){const portfolioItems=document.querySelectorAll('.portfolio-item');const titles={'fdm':['3D Printed Mechanical Parts','Custom Prototype Assembly','Educational Model Kit','Industrial Component Replica'],'sla':['High-Detail Figurine','Dental Model Prototype','Jewelry Design Sample','Complex Mechanical Assembly'],'laser':['Decorative Panel Design','Custom Signage Solution','Architectural Model Component','Precision-Cut Product Parts'],'cnc':['Machined Aluminum Component','Wood Carved Decorative Panel','Custom Fixture Assembly','Precision Manufacturing Sample'],'uv':['UV Printed Acrylic Display','Glass Surface Customization','Wood Product Personalization','Electronic Enclosure Printing']};portfolioItems.forEach(item=>{const category=item.getAttribute('data-category');if(category&&titles[category]){const categoryItems=Array.from(document.querySelectorAll(`.portfolio-item[data-category="${category}"]`));const index=categoryItems.indexOf(item);if(index>=0&&index<titles[category].length){item.setAttribute('data-title',titles[category][index])}}})}